In [42]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as st
import sklearn.datasets

In [43]:
heart = pd.read_csv('/content/heart.csv')

In [45]:
#Tasks: 1-Please apply each of 4 hypothesis testing methods (one/two proportions/means) on the heart dataset for the columns/variables that you will determine.
heart = pd.read_csv('/content/heart.csv')
heart.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

One Proportion Test (Z-test)

In [46]:
#One Proportion Test (Z-test):İkili bir kategorik değişken için iki grup arasındaki oranları karşılaştırmak.
#kalp hastalığı olan erkeklerin oranı, varsayılan bir orandan önemli ölçüde farklıysa.
from statsmodels.stats.proportion import proportions_ztest

# One Proportion Testi için ilgili sütun(erkekler/kadınlar için 'cinsiyet' ve kalp hastalığı için 'hedef')
male_heart_disease = heart[(heart['sex'] == 1) & (heart['target'] == 1)]
n_males = len(heart[heart['sex'] == 1])
p_hypothesis = 0.5  # Varsayılan oran (eşit oranlar için %50)

# Perform the one proportion Z-test
z_stat, p_value = proportions_ztest(len(male_heart_disease), n_males, p_hypothesis)

print("Z-statistic:", z_stat)
print("P-value:", p_value)
#negatif Z-statistiği, birinci gruptaki özelliğin daha küçük olduğunu ve düşük P-değerinin, iki grup arasındaki özelliğin anlamlı bir fark gösterdiğini gösterdiğini söyleyebiliriz. Yani, iki grup arasındaki özelliğin ortalama değerlerinde gerçekten anlamlı bir fark olduğu sonucuna varabiliriz

Z-statistic: -4.286053221733473
P-value: 1.8187543270643557e-05

Two Proportions Test (Z-test)

In [47]:
#İkili bir kategorik değişken için iki bağımsız grup arasındaki oranları karşılaştırmak.
#Kalp hastalığı olan kadın ve erkek oranlarında ise anlamlı bir fark vardır.
female_heart_disease = heart[(heart['sex'] == 0) & (heart['target'] == 1)]
n_females = len(heart[heart['sex'] == 0])

# Perform the two proportions Z-test
count = np.array([len(male_heart_disease), len(female_heart_disease)])
nobs = np.array([n_males, n_females])

z_stat, p_value = proportions_ztest(count, nobs)

print("Z-statistic:", z_stat)
print("P-value:", p_value)

Z-statistic: -8.948390366994612
P-value: 3.607034554789343e-19

One Sample t-test

In [48]:
#Bir örneğin ortalamasını bilinen bir popülasyon ortalamasına veya varsayılan bir değere karşı karşılaştırmak.
#ortalama kolesterol seviyesi, varsayılan bir popülasyon ortalamasından önemli ölçüde farklıysa.
from scipy.stats import ttest_1samp

# Select the relevant column for the one-sample t-test (e.g., 'chol' for cholesterol levels)
sample_mean = heart['chol'].mean()
pop_mean_hypothesis = 240  # Hypothesized population mean

# Perform the one-sample t-test
t_stat, p_value = ttest_1samp(heart['chol'], pop_mean_hypothesis)

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: 3.7232870886745086
P-value: 0.00020736372268666356

Two Sample t-test

In [51]:
#İki bağımsız grubun ortalamalarını karşılaştırmak.
#kalp hastalığı olan ve olmayan hastalar arasında kolesterol düzeylerinde anlamlı bir fark varsa.
# Select the relevant columns for the two-sample t-test (e.g., 'chol' for cholesterol levels and 'target' for heart disease)
from scipy.stats import ttest_ind
chol_with_heart_disease = heart[heart['target'] == 1]['chol']
chol_without_heart_disease = heart[heart['target'] == 0]['chol']

# Perform the two-sample t-test
t_stat, p_value = ttest_ind(chol_with_heart_disease, chol_without_heart_disease)

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: -3.213433097179175
P-value: 0.0013525712504626976

In [ ]:
#TASK2-Please apply each of 4 hypothesis testing methods on the house vote dataset for the columns/variables that you will determine.

In [59]:
votes = pd.read_csv('/content/house-votes-84.csv')

In [60]:
votes

,Class Name,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,?,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,?
2,democrat,?,y,y,?,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,?,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,?,y,y,y,y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,republican,n,n,y,y,y,y,n,n,y,y,n,y,y,y,n,y
431,democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
432,republican,n,?,n,y,y,y,n,n,n,n,y,y,y,y,n,y
433,republican,n,n,n,y,y,y,?,?,?,?,n,y,y,y,n,y
434,republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,?,n

In [63]:
votes.columns

Index(['Class Name', ' handicapped-infants', ' water-project-cost-sharing',
       ' adoption-of-the-budget-resolution', ' physician-fee-freeze',
       ' el-salvador-aid', ' religious-groups-in-schools',
       ' anti-satellite-test-ban', ' aid-to-nicaraguan-contras', ' mx-missile',
       ' immigration', ' synfuels-corporation-cutback', ' education-spending',
       ' superfund-right-to-sue', ' crime', ' duty-free-exports',
       ' export-administration-act-south-africa'],
      dtype='object')

One Proportion Test (Z-test)

In [65]:
#İkili bir kategorik değişken için iki grup arasındaki oranları karşılaştırmak.
#bir konuda 'evet' oyu veren 'demokratların' oranı, varsayılan bir orandan önemli ölçüde farklıysa.
from statsmodels.stats.proportion import proportions_ztest
# Choose a relevant column for the one proportion test (e.g., 'education', 'budget', 'immigration', etc.)
chosen_column = ' education-spending'

# Select the relevant data for Democrats and 'yes' votes
democrats_yes = votes[(votes['Class Name'] == 'democrat') & (votes[chosen_column] == 'y')]
n_democrats = len(votes[votes['Class Name'] == 'democrat'])
p_hypothesis = 0.5  # Hypothesized proportion (e.g., 50% for equal proportions)

# Perform the one proportion Z-test
z_stat, p_value = proportions_ztest(len(democrats_yes), n_democrats, p_hypothesis)

print("Z-statistic:", z_stat)
print("P-value:", p_value)

Z-statistic: -17.470406331925926
P-value: 2.407738491721521e-68

Two Proportions Test (Z-test)

In [67]:
#İkili bir kategorik değişken için iki bağımsız grup arasındaki oranları karşılaştırmak.
#bir konuda 'evet' oyu veren 'demokratlar' ve 'cumhuriyetçiler' oranlarında anlamlı bir fark varsa.
# Select the relevant data for Republicans and 'yes' votes
republicans_yes = votes[(votes['Class Name'] == 'republican') & (votes[chosen_column] == 'y')]
n_republicans = len(votes[votes['Class Name'] == 'republican'])

# Perform the two proportions Z-test
count = np.array([len(democrats_yes), len(republicans_yes)])
nobs = np.array([n_democrats, n_republicans])

z_stat, p_value = proportions_ztest(count, nobs)

print("Z-statistic:", z_stat)
print("P-value:", p_value)

Z-statistic: -13.903116483640462
P-value: 6.064230173925148e-44

One Sample t-test

In [73]:
#Bir örneğin ortalamasını bilinen bir popülasyon ortalamasına veya varsayılan bir değere karşı karşılaştırmak.
#belirli bir konu için ortalama oylama sıklığı varsayımsal bir değerden önemli ölçüde farklıysa.
from scipy.stats import ttest_1samp

# Choose a relevant column for the one-sample t-test (e.g., 'education', 'budget', 'immigration', etc.)
chosen_column = ' education-spending'

# Select the relevant data for the one-sample t-test
sample_mean = votes[chosen_column].map({'y': 1, 'n': -1, '?':0}).mean()
pop_mean_hypothesis = 0.5  # Hypothesized population mean (e.g., 0.5 for equal proportions)

# Perform the one-sample t-test
t_stat, p_value = ttest_1samp(votes[chosen_column].map({'y': 1, 'n': -1, '?':0}), pop_mean_hypothesis)

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: -14.044096067754268
P-value: 3.364706970926524e-37

In [ ]:
#TASK3-Please apply each of 4 hypothesis testing methods on the iris dataset for all of the columns with respect to the species and demonstrate the feature-species pairs that are significantly different from others.

In [76]:
iris= pd.read_csv('/content/iris.csv')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [83]:
#Verinin içinde farklı veri tipleri olduğu için her bir kolon üzerinde uygun hipotez testi uyguladım.

# Loop through all columns and perform the respective hypothesis test for each feature
for column in iris.columns[:-1]:  # Exclude the 'species' column from the loop
    print(f"Feature: {column}")

    # One-Way ANOVA (Numerical Features)
    if iris[column].dtype == 'float64':
        feature_groups = [data[column] for species, data in iris.groupby('species')]
        f_stat, p_value = stats.f_oneway(*feature_groups)
        if p_value < 0.05:
            print("One-Way ANOVA: Significant difference exists.")
        else:
            print("One-Way ANOVA: No significant difference.")

    # Chi-square Test (Categorical Features)
    elif iris[column].dtype == 'object':
        contingency_table = pd.crosstab(iris[column], iris['species'])
        chi2_stat, p_value, dof, expected = stats.chi2_contingency(contingency_table)
        if p_value < 0.05:
            print("Chi-square Test: Significant association exists.")
        else:
            print("Chi-square Test: No significant association.")

    # Two-Proportions Z-Test (Binary Categorical Features)
    elif iris[column].nunique() == 2:
        contingency_table = pd.crosstab(iris[column], iris['species'])
        z_stat, p_value = stats.proportions_ztest(contingency_table, alternative='two-sided')
        if p_value < 0.05:
            print("Two-Proportions Z-Test: Significant difference exists.")
        else:
            print("Two-Proportions Z-Test: No significant difference.")

    # Kruskal-Wallis H Test (Non-Normal Numerical Features)
    else:
        feature_groups = [data[column] for species, data in iris.groupby('species')]
        h_stat, p_value = stats.kruskal(*feature_groups)
        if p_value < 0.05:
            print("Kruskal-Wallis H Test: Significant difference exists.")
        else:
            print("Kruskal-Wallis H Test: No significant difference.")

    print("------------------")

Feature: sepal_length
One-Way ANOVA: Significant difference exists.
------------------
Feature: sepal_width
One-Way ANOVA: Significant difference exists.
------------------
Feature: petal_length
One-Way ANOVA: Significant difference exists.
------------------
Feature: petal_width
One-Way ANOVA: Significant difference exists.
------------------